apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: polling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling
  template:
    metadata:
      labels:
        app: polling
    spec:
      containers:
      - name: polling
        image: polling:v0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: polling
  labels:
    app: polling
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: wallet
