apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wallet
spec:
  replicas: 30
  selector:
    matchLabels:
      app: wallet
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
      - name: wallet
        image: wallet:v0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wallet
  labels:
    app: wallet
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: wallet
